# Generated by Django 5.2 on 2025-04-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "dish", "verbose_name_plural": "dishes"},
        ),
    ]
